spring:
    ai:
      openai:
        api-key: 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
    datasource:
        url: jdbc:postgresql://localhost:5434/pg_nlw
        username: admin
        password: admin
   
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
server:
  port: 8085